### ISSUE TITLE
"405 Method Not Allowed" on User session creation

### ISSUE THREAD

**Issue by sivagollapalli** [drewblessing/gitlab-cli#51]
Hi 

Thanks for helping me. I am try to setup a new CI instance for my projects. I cloned the code and done all my setup. Whenever i try to login it says invalid credentials. Upon debugging I got following information:

```
#<HTTParty::Response:0x10 parsed_response=nil, @response=#<Net::HTTPMethodNotAllowed 405 Method Not Allowed readbody=true>, @headers={"server"=>["nginx"], "date"=>["Mon, 27 Oct 2014 07:36:32 GMT"], "content-type"=>["text/plain"], "transfer-encoding"=>["chunked"], "connection"=>["close"], "status"=>["405 Method Not Allowed"], "allow"=>["OPTIONS, POST"], "cache-control"=>["no-cache"], "x-request-id"=>["d65ded44-b54c-4557-ac36-0f6aab49a288"], "x-runtime"=>["0.003609"]}>
```

How could avoid this problem? Please help me.

**Comment by dblessing** [comment]
I apologize but I no longer maintain this project. I need to update docs to reflect this. I recommend https://github.com/NARKOZ/gitlab as an alternative.
